export const featureStories = [
  { id: "selection", category: "Selection", title: "Pick the atoms you need.", description: "Use the scene tree to select molecular components, hide water, and focus on the structure.", video: "/assets/features/selection.mp4", poster: "/assets/features/selection.jpg", docs: "/docs/surfaces/quick-look" },
  { id: "motion", category: "Trajectories", title: "Follow the motion, frame by frame.", description: "Play a trajectory, pause on a frame, and step forward or back. The Mac app can interpolate between frames for smoother playback.", video: "/assets/features/motion.mp4", poster: "/assets/features/motion.jpg", docs: "/docs/formats" },
  { id: "collections", category: "Collections", title: "Find the compound you need.", description: "Browse structure cards or compare properties in a table. Search the collection and export a subset. Open a multi-pose SDF in 3D to overlay its poses with All.", video: "/assets/features/collections.mp4", poster: "/assets/features/collections.jpg", docs: "/docs/workflows/collections" },
  { id: "space", category: "Chemical Space", title: "See how your molecules compare.", description: "Map a collection by structural similarity. Select a group of points to inspect the corresponding molecules and properties.", video: "/assets/features/space.mp4", poster: "/assets/features/space.jpg", docs: "/docs/workflows/native-compute" },
  { id: "source", category: "Structure and source", title: "Keep the coordinates in sight.", description: "Open the source text beside the molecular view to inspect coordinates and other data in the file.", pending: true, docs: "/docs/surfaces/desktop" },
  { id: "figures", category: "Scientific figures", title: "Make a figure from your structure.", description: "Create vector molecular illustrations with the optional xyzrender engine. Export SVG artwork for papers and slides.", pending: true, docs: "/docs/engines" },
  { id: "agents", category: "Agents", title: "Open a molecule from a conversation.", description: "“Open this PDB and show me the ligand.” With the Burette plugin, your agent can carry out that request in the workspace.", pending: true, docs: "/docs/plugin" },
  { id: "workspace", category: "Molecular workspace", title: "Keep several views open.", description: "Compare structures in tabs and side panels. Open a molecule in Ketcher to edit it and return to the workspace.", pending: true, docs: "/docs/surfaces/desktop" },
];
