export const featureStories = [
  { id: "selection", category: "Selection", title: "Pick the atoms you need.", description: "Draw a lasso around a ligand or pocket. Measure the selection, isolate it, or export it for the next step.", video: "/assets/lasso.mp4", poster: "/assets/lasso-poster.jpg", docs: "/docs/surfaces/quick-look" },
  { id: "motion", category: "Trajectories", title: "Watch the whole movement.", description: "Watch a multi-frame file play as you open it. Pause, step through individual frames, or smooth the motion.", image: "second", scene: "motion", docs: "/docs/formats" },
  { id: "collections", category: "Collections", title: "Find the compound you need.", description: "Browse molecule cards and tables. In the workspace, open an SDF collection in 3D and choose All to view its molecules together.", image: "grid-table", docs: "/docs/workflows/collections" },
  { id: "space", category: "Chemical Space", title: "See how your molecules compare.", description: "Map structural similarities across a collection and select related molecules to inspect together.", image: "chemical-space", docs: "/docs/workflows/native-compute" },
  { id: "source", category: "Structure and source", title: "Keep the coordinates in sight.", description: "Read the source file beside the structure. Burette keeps the text, molecule and file panels together in one workspace.", image: "text-pic", docs: "/docs/surfaces/desktop" },
  { id: "figures", category: "Scientific figures", title: "Make a figure from your structure.", description: "Use the optional xyzrender engine to create vector molecular illustrations for a paper, poster or presentation.", image: "xyzr", docs: "/docs/engines" },
  { id: "agents", category: "Agents", title: "Open a molecule from a conversation.", description: "Ask your agent to open a structure, focus on a ligand or prepare a view. The Burette plugin connects the conversation to the molecular workspace.", video: "/assets/burette-chatgpt-plugin-demo.mp4", poster: "/assets/burette-chatgpt-plugin-demo-poster.jpg", docs: "/docs/plugin" },
  { id: "workspace", category: "Molecular workspace", title: "Keep several views open.", description: "Move between files and tabs, arrange the side panels, and open Ketcher when you need to draw or edit a molecule.", image: "multi", docs: "/docs/surfaces/desktop" },
];
